apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret
type: Opaque
data:
  SECRET_KEY: Y3J5cHRvX3RyYWNrZXJfc3VwZXJfc2VjcmV0X2tleQ==  # base64 encoded "crypto_tracker_super_secret_key"
  POSTGRES_PASSWORD: ZGV2X3Bhc3N3b3Jk  # base64 encoded "dev_password" (must match portfolio-service)
